// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DBAppContext))]
    [Migration("20260112150937_Bookstore")]
    partial class Bookstore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Anh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChiTietMonAnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietMonAnId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("anhs");
                });

            modelBuilder.Entity("API.Models.ChatLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("chatLieus");
                });

            modelBuilder.Entity("API.Models.ChiTietCombo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChiTietMonAnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComboId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietMonAnId");

                    b.HasIndex("ComboId");

                    b.ToTable("chiTietCombos");
                });

            modelBuilder.Entity("API.Models.ChiTietGiamGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChiTietMonAnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChiTietProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GiamGiaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietProductId");

                    b.HasIndex("GiamGiaId");

                    b.ToTable("chiTietGiamGias");
                });

            modelBuilder.Entity("API.Models.ChiTietProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChatLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Gia")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<Guid?>("KichCoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NhaCungCapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoTrang")
                        .HasColumnType("int");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<Guid?>("TheLoaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChatLieuId");

                    b.HasIndex("KichCoId");

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TheLoaiId");

                    b.ToTable("chiTietProducts");
                });

            modelBuilder.Entity("API.Models.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("chucVus");
                });

            modelBuilder.Entity("API.Models.Combo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Gia")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<Guid?>("LoaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiId");

                    b.ToTable("combos");
                });

            modelBuilder.Entity("API.Models.DiaChi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiCuThe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhaCungCapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuanHuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("XaPhuong")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("NhaCungCapId");

                    b.ToTable("diaChis");
                });

            modelBuilder.Entity("API.Models.GiamGia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ApDungSanPham")
                        .HasColumnType("bit");

                    b.Property<bool>("DotGiamGia")
                        .HasColumnType("bit");

                    b.Property<decimal?>("GiaTriToiDa")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<bool?>("Kieu")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhanTramKhuyenMai")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoTienKhuyenMai")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<decimal?>("SoTienToiThieu")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("giamGias");
                });

            modelBuilder.Entity("API.Models.GioHang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ChiTietMonAnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComboId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhachHangid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<decimal>("TongGia")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietMonAnId");

                    b.HasIndex("ComboId");

                    b.HasIndex("KhachHangid");

                    b.ToTable("gioHangs");
                });

            modelBuilder.Entity("API.Models.HinhThucThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("hinhThucThanhToans");
                });

            modelBuilder.Entity("API.Models.HoaDon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiamGiaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("HinhThucThanhToanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KhachHangId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoaiHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<decimal>("TongTienSauKhiGiam")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GiamGiaId");

                    b.HasIndex("HinhThucThanhToanId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("hoaDons");
                });

            modelBuilder.Entity("API.Models.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChiTietMonAnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComboId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoaDonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietMonAnId");

                    b.HasIndex("ComboId");

                    b.HasIndex("HoaDonId");

                    b.ToTable("hoaDonChiTiets");
                });

            modelBuilder.Entity("API.Models.KhachHang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("khachHangs");
                });

            modelBuilder.Entity("API.Models.KichCo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("KichCos");
                });

            modelBuilder.Entity("API.Models.LichSuTrangThai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoaDonChiTietId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonChiTietId");

                    b.ToTable("trangThais");
                });

            modelBuilder.Entity("API.Models.Loai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("loais");
                });

            modelBuilder.Entity("API.Models.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("nguoiDungs");
                });

            modelBuilder.Entity("API.Models.NhaCungCap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("nhaCungCaps");
                });

            modelBuilder.Entity("API.Models.NhaXuatBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("nhaXuatBans");
                });

            modelBuilder.Entity("API.Models.NhanVien", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ChucVuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChucVuId");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("nhanViens");
                });

            modelBuilder.Entity("API.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NhaXuatBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TacGiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NhaXuatBanId");

                    b.HasIndex("TacGiaId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("API.Models.TacGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tacGias");
                });

            modelBuilder.Entity("API.Models.TaiKhoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTaoTk")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("taiKhoans");
                });

            modelBuilder.Entity("API.Models.TheLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("theLoais");
                });

            modelBuilder.Entity("API.Models.Anh", b =>
                {
                    b.HasOne("API.Models.ChiTietProduct", "ChiTietMonAn")
                        .WithMany("Anhs")
                        .HasForeignKey("ChiTietMonAnId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("ChiTietMonAn");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("API.Models.ChiTietCombo", b =>
                {
                    b.HasOne("API.Models.ChiTietProduct", "ChiTietMonAn")
                        .WithMany("ChiTietCombos")
                        .HasForeignKey("ChiTietMonAnId");

                    b.HasOne("API.Models.Combo", "Combo")
                        .WithMany("ChiTietCombos")
                        .HasForeignKey("ComboId");

                    b.Navigation("ChiTietMonAn");

                    b.Navigation("Combo");
                });

            modelBuilder.Entity("API.Models.ChiTietGiamGia", b =>
                {
                    b.HasOne("API.Models.ChiTietProduct", "ChiTietProduct")
                        .WithMany("ChiTietGiamGias")
                        .HasForeignKey("ChiTietProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.GiamGia", "GiamGia")
                        .WithMany("chiTietGiamGias")
                        .HasForeignKey("GiamGiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietProduct");

                    b.Navigation("GiamGia");
                });

            modelBuilder.Entity("API.Models.ChiTietProduct", b =>
                {
                    b.HasOne("API.Models.ChatLieu", "ChatLieu")
                        .WithMany("ChiTietMonAn")
                        .HasForeignKey("ChatLieuId");

                    b.HasOne("API.Models.KichCo", "KichCo")
                        .WithMany("chitietproducts")
                        .HasForeignKey("KichCoId");

                    b.HasOne("API.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NhaCungCapId");

                    b.HasOne("API.Models.Product", "Product")
                        .WithMany("ChiTietMonAns")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.TheLoai", "TheLoai")
                        .WithMany("chitietproducts")
                        .HasForeignKey("TheLoaiId");

                    b.Navigation("ChatLieu");

                    b.Navigation("KichCo");

                    b.Navigation("NhaCungCap");

                    b.Navigation("Product");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("API.Models.Combo", b =>
                {
                    b.HasOne("API.Models.Loai", "Loai")
                        .WithMany("Combos")
                        .HasForeignKey("LoaiId");

                    b.Navigation("Loai");
                });

            modelBuilder.Entity("API.Models.DiaChi", b =>
                {
                    b.HasOne("API.Models.NguoiDung", "NguoiDung")
                        .WithMany("DiaChis")
                        .HasForeignKey("NguoiDungId");

                    b.HasOne("API.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("DiaChis")
                        .HasForeignKey("NhaCungCapId");

                    b.Navigation("NguoiDung");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("API.Models.GioHang", b =>
                {
                    b.HasOne("API.Models.ChiTietProduct", "ChiTietMonAn")
                        .WithMany("GioHangs")
                        .HasForeignKey("ChiTietMonAnId");

                    b.HasOne("API.Models.Combo", "Combo")
                        .WithMany("GioHangs")
                        .HasForeignKey("ComboId");

                    b.HasOne("API.Models.KhachHang", "KhachHang")
                        .WithMany("GioHangs")
                        .HasForeignKey("KhachHangid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietMonAn");

                    b.Navigation("Combo");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("API.Models.HoaDon", b =>
                {
                    b.HasOne("API.Models.GiamGia", "GiamGia")
                        .WithMany("hoaDons")
                        .HasForeignKey("GiamGiaId");

                    b.HasOne("API.Models.HinhThucThanhToan", "HinhThucThanhToan")
                        .WithMany("HoaDon")
                        .HasForeignKey("HinhThucThanhToanId");

                    b.HasOne("API.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangId");

                    b.HasOne("API.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("NhanVienId");

                    b.Navigation("GiamGia");

                    b.Navigation("HinhThucThanhToan");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("API.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("API.Models.ChiTietProduct", "ChiTietMonAn")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("ChiTietMonAnId");

                    b.HasOne("API.Models.Combo", "Combo")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("ComboId");

                    b.HasOne("API.Models.HoaDon", "HoaDon")
                        .WithMany("hoaDonChiTiets")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietMonAn");

                    b.Navigation("Combo");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("API.Models.KhachHang", b =>
                {
                    b.HasOne("API.Models.NguoiDung", "NguoiDung")
                        .WithOne("KhachHang")
                        .HasForeignKey("API.Models.KhachHang", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("API.Models.LichSuTrangThai", b =>
                {
                    b.HasOne("API.Models.HoaDonChiTiet", "HoaDonChiTiet")
                        .WithMany("lichSuTrangThais")
                        .HasForeignKey("HoaDonChiTietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDonChiTiet");
                });

            modelBuilder.Entity("API.Models.NhanVien", b =>
                {
                    b.HasOne("API.Models.ChucVu", "ChucVu")
                        .WithMany("NhanVien")
                        .HasForeignKey("ChucVuId");

                    b.HasOne("API.Models.NguoiDung", "NguoiDung")
                        .WithOne("NhanVien")
                        .HasForeignKey("API.Models.NhanVien", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("API.Models.Product", b =>
                {
                    b.HasOne("API.Models.NhaXuatBan", "NhaXuatBan")
                        .WithMany("Products")
                        .HasForeignKey("NhaXuatBanId");

                    b.HasOne("API.Models.TacGia", "TheLoai")
                        .WithMany("MonAns")
                        .HasForeignKey("TacGiaId");

                    b.Navigation("NhaXuatBan");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("API.Models.TaiKhoan", b =>
                {
                    b.HasOne("API.Models.NguoiDung", "NguoiDung")
                        .WithOne()
                        .HasForeignKey("API.Models.TaiKhoan", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("API.Models.ChatLieu", b =>
                {
                    b.Navigation("ChiTietMonAn");
                });

            modelBuilder.Entity("API.Models.ChiTietProduct", b =>
                {
                    b.Navigation("Anhs");

                    b.Navigation("ChiTietCombos");

                    b.Navigation("ChiTietGiamGias");

                    b.Navigation("GioHangs");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("API.Models.ChucVu", b =>
                {
                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("API.Models.Combo", b =>
                {
                    b.Navigation("ChiTietCombos");

                    b.Navigation("GioHangs");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("API.Models.GiamGia", b =>
                {
                    b.Navigation("chiTietGiamGias");

                    b.Navigation("hoaDons");
                });

            modelBuilder.Entity("API.Models.HinhThucThanhToan", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("API.Models.HoaDon", b =>
                {
                    b.Navigation("hoaDonChiTiets");
                });

            modelBuilder.Entity("API.Models.HoaDonChiTiet", b =>
                {
                    b.Navigation("lichSuTrangThais");
                });

            modelBuilder.Entity("API.Models.KhachHang", b =>
                {
                    b.Navigation("GioHangs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("API.Models.KichCo", b =>
                {
                    b.Navigation("chitietproducts");
                });

            modelBuilder.Entity("API.Models.Loai", b =>
                {
                    b.Navigation("Combos");
                });

            modelBuilder.Entity("API.Models.NguoiDung", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("API.Models.NhaCungCap", b =>
                {
                    b.Navigation("DiaChis");
                });

            modelBuilder.Entity("API.Models.NhaXuatBan", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("API.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("API.Models.Product", b =>
                {
                    b.Navigation("ChiTietMonAns");
                });

            modelBuilder.Entity("API.Models.TacGia", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("API.Models.TheLoai", b =>
                {
                    b.Navigation("chitietproducts");
                });
#pragma warning restore 612, 618
        }
    }
}
